### ISSUE TITLE
Error in the pkg-config libdir variable (CMake)

### ISSUE THREAD

**Issue by vmagnin** [gha3mi/forimage#16]
https://github.com/gha3mi/forimage/blob/9c123af62a96b99c8eb08bb5b0fe25d599612eb9/install/template.pc#L2C21-L2C46

In `install/template.pc`:
```txt
libdir = ${prefix}/@CMAKE_INSTALL_FULL_LIBDIR@
```
should be instead:
```txt
libdir = ${prefix}/@CMAKE_INSTALL_LIBDIR@
```

Similar to https://github.com/vmagnin/forcolormap/issues/19

**Comment by gha3mi** [comment]
Thanks! The issue has been fixed.
